import prisma from "../../PrismaConnection";
import { HelpdeskHardwareMaster } from "../../../generated/prisma";

// HardwareMaster class is used for encapsulating Hardware Master properties with all of its method for creating, updating or retrieving data from database. 
// It is created based on HelpdeskHardwareMaster table structure in database and to align with the type created by Prisma ORM. 
class HardwareMaster {
  readonly code: string;
  readonly descrption: string;
  readonly isActive: boolean;

  // Constructor for initializing HardwareMaster class.
  constructor(code: string = "", descrption: string = "", isActive: boolean = false) {
    this.code = code;
    this.descrption = descrption;
    this.isActive = isActive;
  };  

  // Second constructor of HardwareMaster class which uses HelpdeskHardwareMaster type (generated from Prisma ORM based on the corresponding table structure) as parameter. 
  static createFromType = (data: HelpdeskHardwareMaster) => {
    return new HardwareMaster(data.Code, data.Descrption, data.IsActive === "Y");
  };

  // Converting HardwareMaster class back to HelpdeskHardwareMaster type for database operations purpose to utilizing built-in database operation for each type 
  // as Prisma ORM has provided all database operations for each of its created type. 
  createAsType = () => {
    const data: HelpdeskHardwareMaster = {
      Code: this.code,
      Descrption: this.descrption,
      IsActive: this.isActive ? "Y" : "N"
    };
    return data;
  };

  // Check on database for the table on whether the "code" value provided by user is already exists in database. Code is the primary key 
  // of HelpdeskHardwareMaster table, thus the value couldn't be redundant.
  static checkHardwareCodeAvailability = async (code: string) => {
    return !(await prisma.helpdeskHardwareMaster.findFirst({
      where: { Code: code }
    }));
  };

  // Method acts as interface to retrieve all Hardware Master data from database table using method generated by Prisma ORM.
  static getHardwareMasterList = async () => {
    const getHardwareMasterListQuery: HelpdeskHardwareMaster[] = await prisma.helpdeskHardwareMaster.findMany();
    return getHardwareMasterListQuery.map(hardware => HardwareMaster.createFromType(hardware));
  };

  // Method acts as interface to insert Hardware Master data into table using method generated by Prisma ORM.
  createHardwareMaster = async () => {
    return prisma.helpdeskHardwareMaster.create({
      data: this.createAsType()
    });
  };

  // Method acts as interface to update Hardware Master data into table using method generated by Prisma ORM.
  updateHardwareMaster = async () => {
    return prisma.helpdeskHardwareMaster.update({
      where: { Code: this.code },
      data: this.createAsType()
    });
  };
};

export default HardwareMaster;
